version: "3"
services:
  business-app:
    container_name: auth-business-app
    build: ./business-app
    environment: 
      DJANGO_SECRET_KEY: lksjauasujoiru0923842jrMKJF
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: business_app
      DJANGO_DB_USER: business_app_admin
      DJANGO_DB_PASSWORD: admin
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:latest
    container_name: auth-pg-db
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker-db-init-scripts:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data
  